Array.prototype.remove=function(value){if(this.indexOf(value)!==-1){this.splice(this.indexOf(value),1);return true;}else{return false;}}
function generateUrlParameters(url,current_parameters,is_remove_unused_parameters){var url1=new Url(url);var query=current_parameters[wp_localize_script_autocomplete.SEARCH_PARAMETER_Q]||'';if(query!==''){url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_Q]=query;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_Q];}
for(var index=0;;index++){if(undefined===url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ+'['+index+']']){break;}else{delete url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ+'['+index+']'];}}
var query_fields=current_parameters[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ]||[];for(var index in query_fields){url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ+'['+index+']']=query_fields[index];}
var sort=current_parameters[wp_localize_script_autocomplete.SEARCH_PARAMETER_SORT]||'';if(sort!==''){url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_SORT]=sort;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_SORT];}
var paged=current_parameters[wp_localize_script_autocomplete.SEARCH_PARAMETER_PAGE]||'';if(paged!==''){url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_PAGE]=paged;}else if(is_remove_unused_parameters){delete url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_PAGE];}
delete url1.query[wp_localize_script_autocomplete.SEARCH_PARAMETER_SEARCH];return'?'+url1.query.toString();}
window.addEventListener("popstate",function(e){if(e.state){call_ajax_search(window.location.search,false);}});function get_ui_facets_state(){state=[];jQuery('.select_opt.checked').each(function(){opts=jQuery(this).attr('id');if(opts!=='wpsolr_remove_facets'){state.push(opts);}});return state;}
function get_ui_selection(){var result={};result[wp_localize_script_autocomplete.SEARCH_PARAMETER_Q]=jQuery('#search_que').val()||'';result[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ]=get_ui_facets_state();result[wp_localize_script_autocomplete.SEARCH_PARAMETER_SORT]=jQuery('.select_field').val()||'';result[wp_localize_script_autocomplete.SEARCH_PARAMETER_PAGE]=jQuery('#paginate').val()||'';return result;}
function call_ajax_search(selection_parameters,is_change_url){jQuery('.loading_res').css('display','block');jQuery('.results-by-facets').css('display','none');var url_parameters=selection_parameters;if(selection_parameters instanceof Object){var parameters=get_ui_selection();jQuery.extend(parameters,selection_parameters);url_parameters=generateUrlParameters(window.location.href,parameters,true);}
if(wp_localize_script_autocomplete.is_url_redirect){var url_base=window.location.href.split("?")[0];var url=url_base.replace(/\/page\/\d+/,'');window.location.href=url+url_parameters;return;}
if(is_change_url&&wp_localize_script_autocomplete.is_show_url_parameters){var state={url:url_parameters};window.history.pushState(state,'',state.url);}
var data={action:'return_solr_results',url_parameters:url_parameters};jQuery.ajax({url:wp_localize_script_autocomplete.ajax_url,type:"post",data:data,success:function(data1){jQuery('.loading_res').css('display','none');jQuery('.results-by-facets').css('display','block');data=JSON.parse(data1);jQuery('.results-by-facets').html(data[0]);jQuery('.paginate_div').html(data[1]);jQuery('.res_info').html(data[2]);jQuery('#res_facets').html(data[3]);},error:function(){jQuery('.loading_res').css('display','none');jQuery('.results-by-facets').css('display','block');},always:function(){}});}
jQuery(document).ready(function(){jQuery(wp_localize_script_autocomplete.wpsolr_autocomplete_selector).off();jQuery(wp_localize_script_autocomplete.wpsolr_autocomplete_selector).prop('autocomplete','off');jQuery(document).on('focus',wp_localize_script_autocomplete.wpsolr_autocomplete_selector,function(event){event.preventDefault();var wp_ajax_action=wp_localize_script_autocomplete.wpsolr_autocomplete_action;var wp_ajax_nonce=jQuery(wp_localize_script_autocomplete.wpsolr_autocomplete_nonce_selector).val();var mythis=this;jQuery(this).typeahead({ajax:{url:wp_localize_script_autocomplete.ajax_url,triggerLength:1,method:"post",loadingClass:"loading-circle",preDispatch:function(query){jQuery(mythis).addClass('loading_sugg');return{action:wp_ajax_action,word:query,security:wp_ajax_nonce}},preProcess:function(data){jQuery(mythis).removeClass('loading_sugg');return data;}}});})
jQuery(document).on('click','.select_opt',function(){jQuery('#paginate').val('');var state=[];if(jQuery(this).attr('id')==='wpsolr_remove_facets'){jQuery('.select_opt').removeClass('checked');jQuery(this).addClass('checked');}else{is_already_selected=jQuery(this).hasClass('checked');var facet_name=jQuery(this).attr('id').split(":")[0];if(is_already_selected){jQuery(this).removeClass('checked');jQuery(this).closest("ul").children().find("[id^="+facet_name+"]").removeClass('checked');}else{jQuery(this).parents("li").children(".select_opt").addClass('checked');}
state=get_ui_facets_state();}
var parameter={};parameter[wp_localize_script_autocomplete.SEARCH_PARAMETER_FQ]=state;call_ajax_search(parameter,true);});jQuery(document).on('change','.select_field',function(){jQuery('#paginate').val('');sort_value=jQuery(this).val();var parameter={};parameter[wp_localize_script_autocomplete.SEARCH_PARAMETER_SORT]=sort_value;call_ajax_search(parameter,true);});jQuery(document).on('click','.paginate',function(){page_number=jQuery(this).attr('id');jQuery('#paginate').val(page_number);var parameter={};parameter[wp_localize_script_autocomplete.SEARCH_PARAMETER_PAGE]=page_number;call_ajax_search(parameter,true);});});